name: my_accordion
description: accordion expansion widget.
version: 0.0.1
author: Furkan Köseoğlu<furkankoseoglu65@gmail.com>
homepage: https://github.com/furkanksl/MFKAccordion.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
